from typing import Optional, List
from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import PlainTextResponse
from sqlalchemy.orm import Session

from app.db.postgres import get_db
from app.models.report import Report
from app.models.user import User
from app.schemas.report import ReportGenerateRequest, ReportResponse
from app.middleware.auth import require_authenticated_user
from app.services.report_service import generate_compliance_report
from app.utils.helpers import standard_response

router = APIRouter(prefix="/reports", tags=["Statutory Reports"])

def serialize_report(r: Report) -> dict:
    return {
        "id": r.id,
        "title": r.title,
        "type": r.type,
        "generatedDate": r.generated_date,
        "generatedBy": r.generated_by,
        "period": r.period,
        "status": r.status,
        "fileFormat": r.file_format,
        "format": r.file_format,
        "downloadUrl": r.download_url
    }

@router.get("")
async def get_all_reports(
    type_filter: Optional[str] = Query(None, alias="type"),
    current_user: User = Depends(require_authenticated_user),
    db: Session = Depends(get_db)
):
    """List generated statutory reports."""
    query = db.query(Report)
    if type_filter and type_filter != "All":
        query = query.filter(Report.type.ilike(type_filter))

    reports = query.order_by(Report.created_at.desc()).all()
    results = [serialize_report(r) for r in reports]
    return standard_response(success=True, data=results)

@router.post("/generate")
async def generate_report_endpoint(
    req: ReportGenerateRequest,
    current_user: User = Depends(require_authenticated_user),
    db: Session = Depends(get_db)
):
    """Generate new statutory compliance report from authoritative data."""
    rep = generate_compliance_report(req, db, current_user)
    return standard_response(
        success=True,
        message="Statutory report generated and archived",
        data=serialize_report(rep)
    )

@router.get("/{report_id}/download")
async def download_report(
    report_id: str,
    db: Session = Depends(get_db)
):
    """Download statutory report document."""
    rep = db.query(Report).filter(Report.id == report_id).first()
    if not rep:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")

    content = f"""KOYLA DRISHTI - STATUTORY COMPLIANCE DOSSIER
Title: {rep.title}
Report ID: {rep.id}
Type: {rep.type}
Period: {rep.period}
Generated By: {rep.generated_by}
Generated Date: {rep.generated_date}
Status: {rep.status}

CONFIDENTIAL MINISTRY OF COAL / DGMS RECORD
All parameters and compliance scores certified by statutory oversight rules.
"""
    return PlainTextResponse(
        content=content,
        headers={"Content-Disposition": f'attachment; filename="{rep.id}_{rep.type.lower()}.txt"'}
    )
