import { 
  Mine, 
  AIAlert, 
  Inspection, 
  Violation, 
  CorrectiveAction, 
  MineDocument, 
  ReportItem, 
  NotificationItem,
  User 
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'USR-001',
    name: 'Shri A. K. Sen, IAS',
    email: 'admin@coal.gov.in',
    role: 'admin',
    designation: 'Joint Secretary (Governance)',
    organization: 'Ministry of Coal, New Delhi',
    avatarText: 'AS',
    status: 'active',
    lastActive: 'Today, 14:20'
  },
  {
    id: 'USR-002',
    name: 'Rajesh Sharma, DGMS',
    email: 'inspector@dgms.gov.in',
    role: 'inspector',
    designation: 'Director of Mines Safety (East Zone)',
    organization: 'Directorate General of Mines Safety',
    avatarText: 'RS',
    phone: '+91 98451 22910',
    status: 'active',
    lastActive: 'Today, 15:45'
  },
  {
    id: 'USR-003',
    name: 'Bharat Coking Coal Ltd. Authority',
    email: 'mine@bccl.gov.in',
    role: 'mine',
    designation: 'General Manager (Safety & Compliance)',
    organization: 'Bharat Coking Coal Limited (BCCL)',
    avatarText: 'BM',
    mineId: 'KD-104',
    phone: '+91 94311 02847',
    status: 'active',
    lastActive: 'Today, 16:10'
  },
  {
    id: 'USR-004',
    name: 'Sunil Verma',
    email: 's.verma@dgms.gov.in',
    role: 'inspector',
    designation: 'Dy. Director (Environmental Audit)',
    organization: 'DGMS Bhubaneswar Region',
    avatarText: 'SV',
    phone: '+91 97760 11982',
    status: 'active',
    lastActive: 'Yesterday'
  },
  {
    id: 'USR-005',
    name: 'Anil Kumar',
    email: 'a.kumar@dgms.gov.in',
    role: 'inspector',
    designation: 'Inspector of Mines (Electrical/Mech)',
    organization: 'DGMS Bilaspur Region',
    avatarText: 'AK',
    phone: '+91 98261 44512',
    status: 'active',
    lastActive: 'Today, 11:30'
  }
];

export const INITIAL_MINES: Mine[] = [
  {
    id: 'KD-104',
    name: 'Bharat Coking Coal Mine (Dhanbad)',
    operator: 'Bharat Coking Coal Limited (BCCL)',
    mineType: 'Coking Coal (Opencast & UG)',
    district: 'Dhanbad',
    state: 'Jharkhand',
    complianceScore: 88,
    riskLevel: 'Medium',
    status: 'Compliant',
    lastInspection: '12 Aug 2026',
    nextInspection: '08 Sep 2026',
    address: 'Koyla Bhawan, Koyla Nagar, Dhanbad, Jharkhand - 826005',
    contactOfficer: 'Er. P. K. Mishra (Agent / GM)',
    contactEmail: 'gm.compliance@bccl.gov.in',
    coordinates: { lat: 23.7957, lng: 86.4304 },
    activeViolationsCount: 3
  },
  {
    id: 'KD-118',
    name: 'Talcher Colliery Complex',
    operator: 'Mahanadi Coalfields Limited (MCL)',
    mineType: 'Non-Coking Thermal Coal',
    district: 'Angul',
    state: 'Odisha',
    complianceScore: 74,
    riskLevel: 'High',
    status: 'Under Review',
    lastInspection: '24 Jul 2026',
    nextInspection: '09 Sep 2026',
    address: 'Talcher Coalfields Area, Jagannath PO, Angul, Odisha - 759148',
    contactOfficer: 'Dr. Debasis Mohapatra (Safety Officer)',
    contactEmail: 'safety.talcher@mcl.gov.in',
    coordinates: { lat: 20.9500, lng: 85.2167 },
    activeViolationsCount: 4
  },
  {
    id: 'KD-143',
    name: 'Korba West Mega Opencast Project',
    operator: 'South Eastern Coalfields Limited (SECL)',
    mineType: 'Non-Coking Coal (Opencast)',
    district: 'Korba',
    state: 'Chhattisgarh',
    complianceScore: 61,
    riskLevel: 'High',
    status: 'Non-Compliant',
    lastInspection: '07 Sep 2026',
    nextInspection: '10 Sep 2026',
    address: 'SECL Korba Area, Kusmunda P.O., Korba, CG - 495677',
    contactOfficer: 'S. N. Chandrakar (GM Operations)',
    contactEmail: 'kusmunda.env@secl.gov.in',
    coordinates: { lat: 22.3595, lng: 82.7501 },
    activeViolationsCount: 5
  },
  {
    id: 'KD-169',
    name: 'Singareni No. 2 Incline & OCP',
    operator: 'Singareni Collieries Company Limited (SCCL)',
    mineType: 'High Grade Non-Coking',
    district: 'Bhadradri Kothagudem',
    state: 'Telangana',
    complianceScore: 92,
    riskLevel: 'Low',
    status: 'Compliant',
    lastInspection: '18 Aug 2026',
    nextInspection: '14 Sep 2026',
    address: 'Kothagudem Collieries, Bhadradri District, Telangana - 507101',
    contactOfficer: 'V. Venkateshwarlu (Dir Mine Safety)',
    contactEmail: 'compliance@scclmines.com',
    coordinates: { lat: 17.5500, lng: 80.6167 },
    activeViolationsCount: 1
  },
  {
    id: 'KD-202',
    name: 'Jharia Block IV Underground Seam',
    operator: 'Eastern Coalfields Limited (ECL)',
    mineType: 'Prime Coking Coal (UG)',
    district: 'Dhanbad',
    state: 'Jharkhand',
    complianceScore: 78,
    riskLevel: 'Medium',
    status: 'Under Review',
    lastInspection: '01 Aug 2026',
    nextInspection: '16 Sep 2026',
    address: 'Jharia Coalfield Basin, Dhanbad, Jharkhand - 828111',
    contactOfficer: 'M. K. Bannerjee (Chief Mining Engineer)',
    contactEmail: 'jharia.safety@easterncoal.gov.in',
    coordinates: { lat: 23.7424, lng: 86.4131 },
    activeViolationsCount: 2
  },
  {
    id: 'KD-215',
    name: 'Gevra Expansion Opencast Mine',
    operator: 'South Eastern Coalfields Limited (SECL)',
    mineType: 'High Capacity Opencast',
    district: 'Korba',
    state: 'Chhattisgarh',
    complianceScore: 85,
    riskLevel: 'Low',
    status: 'Compliant',
    lastInspection: '20 Jul 2026',
    nextInspection: '22 Sep 2026',
    address: 'Gevra Project PO, Korba District, Chhattisgarh - 495452',
    contactOfficer: 'R. K. Tiwari (Project Officer)',
    contactEmail: 'gevra.env@secl.gov.in',
    coordinates: { lat: 22.3300, lng: 82.5900 },
    activeViolationsCount: 1
  },
  {
    id: 'KD-240',
    name: 'Piprawar Coal Washery & Pit',
    operator: 'Central Coalfields Limited (CCL)',
    mineType: 'Beneficiation & Semi-Coking',
    district: 'Chatra',
    state: 'Jharkhand',
    complianceScore: 81,
    riskLevel: 'Medium',
    status: 'Compliant',
    lastInspection: '14 Aug 2026',
    nextInspection: '25 Sep 2026',
    address: 'Piprawar Area, Bachra PO, Chatra, Jharkhand - 829201',
    contactOfficer: 'Amitabh Sen (Safety Head)',
    contactEmail: 'piprawar.audit@centralcoalfields.in',
    coordinates: { lat: 23.8200, lng: 85.0400 },
    activeViolationsCount: 2
  },
  {
    id: 'KD-255',
    name: 'Belpahar OC Mine',
    operator: 'Mahanadi Coalfields Limited (MCL)',
    mineType: 'Thermal Grade Opencast',
    district: 'Jharsuguda',
    state: 'Odisha',
    complianceScore: 68,
    riskLevel: 'High',
    status: 'Under Review',
    lastInspection: '05 Jul 2026',
    nextInspection: '18 Sep 2026',
    address: 'Ib Valley Area, Belpahar, Jharsuguda, Odisha - 768218',
    contactOfficer: 'K. C. Nayak (Mine Manager)',
    contactEmail: 'safety.ibvalley@mcl.gov.in',
    coordinates: { lat: 21.8200, lng: 83.8600 },
    activeViolationsCount: 3
  }
];

export const INITIAL_ALERTS: AIAlert[] = [
  {
    id: 'ALT-1092',
    title: 'Unauthorized Pit Expansion Beyond Lease Boundary',
    mineId: 'KD-169',
    mineName: 'Singareni No. 2 Incline & OCP',
    location: 'Bhadradri Kothagudem, Telangana',
    category: 'Expansion',
    confidenceScore: 92,
    severity: 'High',
    detectedAt: '2 hours ago',
    status: 'Under Review',
    assignedInspector: 'Rajesh Sharma, DGMS',
    inspectorId: 'USR-002',
    detectedIssue: 'Sentinel-2 multispectral surface imagery comparison reveals an outward overburden progression of 42 meters beyond demarcated Geo-fence polygon Sector 4B.',
    supportingEvidence: 'High resolution satellite overlay timestamp 2026-09-04 10:45 IST; Normalized Difference Vegetation Index (NDVI) deficit detected.',
    recommendedAction: 'Immediate DGMS field surveyor verification; issue warning notice to halt machinery in Sector 4B.',
    satelliteCoordinates: '17.5521° N, 80.6198° E'
  },
  {
    id: 'ALT-1088',
    title: 'Critical Particulate Matter PM10 Continuous Threshold Exceedance',
    mineId: 'KD-118',
    mineName: 'Talcher Colliery Complex',
    location: 'Angul, Odisha',
    category: 'Environment',
    confidenceScore: 87,
    severity: 'High',
    detectedAt: '5 hours ago',
    status: 'Assigned',
    assignedInspector: 'Sunil Verma',
    inspectorId: 'USR-004',
    detectedIssue: 'Continuous Ambient Air Quality Monitoring Station (CAAQMS Station 2) recorded PM10 > 380 µg/m³ for 6 consecutive operational hours (standard limit 100 µg/m³).',
    supportingEvidence: 'Automated IoT telemetry log data stream from South Haul Road sensor array.',
    recommendedAction: 'Mandatory mist spray cannon activation along haul road; verify dust-suppression vehicle logbooks.',
    satelliteCoordinates: '20.9515° N, 85.2210° E'
  },
  {
    id: 'ALT-1074',
    title: 'Underground Methane & Carbon Monoxide Sensor Drift Warning',
    mineId: 'KD-202',
    mineName: 'Jharia Block IV Underground Seam',
    location: 'Dhanbad, Jharkhand',
    category: 'Safety',
    confidenceScore: 94,
    severity: 'Critical',
    detectedAt: '1 day ago',
    status: 'Under Review',
    assignedInspector: 'Rajesh Sharma, DGMS',
    inspectorId: 'USR-002',
    detectedIssue: 'Ventilation telemetry in Seam 14 Panel C indicates transient methane spikes reaching 1.15% coupled with telemetry loss on secondary CH4 transducer.',
    supportingEvidence: 'DGMS automated SCADA telemetry monitor; 14 packet dropouts detected in 24 hours.',
    recommendedAction: 'Urgent underground inspection by DGMS ventilation inspector; test manual methanometer before next blasting shift.',
    satelliteCoordinates: '23.7441° N, 86.4152° E'
  },
  {
    id: 'ALT-1065',
    title: 'Statutory Heavy Earth Moving Machinery (HEMM) Fitness Certificate Expired',
    mineId: 'KD-143',
    mineName: 'Korba West Mega Opencast Project',
    location: 'Korba, Chhattisgarh',
    category: 'Equipment',
    confidenceScore: 98,
    severity: 'Medium',
    detectedAt: '1 day ago',
    status: 'New',
    assignedInspector: 'Anil Kumar',
    inspectorId: 'USR-005',
    detectedIssue: '3 Hydraulic Shovels (Cat 6020B) operating without renewed Directorate General of Factory Inspection stability & brake test certification.',
    supportingEvidence: 'Equipment log comparison against National Mine Asset Database registry.',
    recommendedAction: 'Issue formal query to Mine Manager; impound machinery from highwall extraction till certificate upload.',
    satelliteCoordinates: '22.3610° N, 82.7540° E'
  },
  {
    id: 'ALT-1051',
    title: 'Quarterly Ground Water Recharge Report Delay',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    location: 'Dhanbad, Jharkhand',
    category: 'Documentation',
    confidenceScore: 84,
    severity: 'Low',
    detectedAt: '2 days ago',
    status: 'Verified',
    assignedInspector: 'Rajesh Sharma, DGMS',
    inspectorId: 'USR-002',
    detectedIssue: 'Central Ground Water Authority (CGWA) piezometer water table monitoring report for Q2 2026 pending upload past due date (31 Aug 2026).',
    supportingEvidence: 'Portal submission schedule tracker; zero file submission in CGWA portal connector.',
    recommendedAction: 'Automated notice sent to BCCL Environmental Cell to submit hydrologist verified logs within 7 days.',
    satelliteCoordinates: '23.7960° N, 86.4312° E'
  },
  {
    id: 'ALT-1040',
    title: 'Overburden Bench Slope Stability Angle Anomaly',
    mineId: 'KD-255',
    mineName: 'Belpahar OC Mine',
    location: 'Jharsuguda, Odisha',
    category: 'Safety',
    confidenceScore: 91,
    severity: 'High',
    detectedAt: '3 days ago',
    status: 'New',
    assignedInspector: 'Sunil Verma',
    inspectorId: 'USR-004',
    detectedIssue: 'Drone LiDAR point-cloud survey indicates Sector 3 Waste Dump slope angle stands at 41.5° exceeding statutory safety limit of 37.5°.',
    supportingEvidence: 'CMPDI Drone survey terrain mesh comparison dated 28 Aug 2026.',
    recommendedAction: 'Immediate slope terracing; install displacement prism sensors along dump crest.',
    satelliteCoordinates: '21.8250° N, 83.8640° E'
  }
];

export const INITIAL_INSPECTIONS: Inspection[] = [
  {
    id: 'INS-2408',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    inspectorName: 'Rajesh Sharma, DGMS',
    inspectorId: 'USR-002',
    inspectionType: 'Safety',
    date: '08 Sep 2026',
    time: '10:30 AM',
    status: 'Scheduled',
    priority: 'Priority',
    purpose: 'Routine statutory safety audit, slope bench verification, and worker PPE compliance.',
    checklistItems: [
      { id: 'chk-1', label: 'Check underground ventilation shaft fan velocity & air quantity', completed: true, findings: 'Velocity within safe norms: 4.8 m/s' },
      { id: 'chk-2', label: 'Verify methane drainage monitoring logs at Seam 11', completed: true, findings: 'Digital sensors functioning normally' },
      { id: 'chk-3', label: 'Inspect bench height and width ratio in Opencast Pit #2', completed: false, findings: 'Bench height requires terracing verification' },
      { id: 'chk-4', label: 'Inspect worker refuge chambers and emergency breathing apparatuses', completed: false },
      { id: 'chk-5', label: 'Verify heavy vehicle haul road berm height (min 1.5x tire height)', completed: false }
    ],
    observations: 'Preparation under progress. BCCL safety manager notified.',
    evidenceFilesCount: 0
  },
  {
    id: 'INS-2384',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    inspectorName: 'Sunil Verma',
    inspectorId: 'USR-004',
    inspectionType: 'Environment',
    date: '12 Aug 2026',
    time: '11:15 AM',
    status: 'Completed',
    priority: 'Routine',
    purpose: 'Statutory monsoon drainage silt trap inspection and active settling pond overflow audit.',
    checklistItems: [
      { id: 'chk-1', label: 'Check garland drain silt trap depth & clearance', completed: true, findings: 'Garland drains cleared across 4.2 km perimeter.' },
      { id: 'chk-2', label: 'Examine sedimentation basin retention capacity', completed: true, findings: 'Basin retention capacity verified at 45,000 cu.m.' },
      { id: 'chk-3', label: 'Sample mine sump discharge water quality for heavy metals', completed: true, findings: 'Lab report shows pH 7.2, TSS 42 mg/L within permissible limits.' }
    ],
    observations: 'Monsoon preparedness adequate. Recommend bi-weekly silt skimming of Basin #3.',
    recommendations: 'Continue digital telemetry transmission to Jharkhand State Pollution Control Board.',
    evidenceFilesCount: 4
  },
  {
    id: 'INS-2418',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    inspectorName: 'Rajesh Sharma, DGMS',
    inspectorId: 'USR-002',
    inspectionType: 'Follow-up',
    date: '16 Sep 2026',
    time: '02:00 PM',
    status: 'Scheduled',
    priority: 'Priority',
    purpose: 'Physical verification of Western Sector bench slope terracing rectification (VIO-1024).',
    checklistItems: [
      { id: 'chk-1', label: 'Verify Western Sector bench angle reduction to 35 degrees', completed: false },
      { id: 'chk-2', label: 'Inspect CIMFR digital tiltmeter array readings on upper berm', completed: false },
      { id: 'chk-3', label: 'Validate geotechnical stability clearance report', completed: false }
    ],
    observations: 'Follow-up verification audit scheduled post-remediation deadline.',
    evidenceFilesCount: 0
  },
  {
    id: 'INS-2411',
    mineId: 'KD-118',
    mineName: 'Talcher Colliery Complex',
    inspectorName: 'Sunil Verma',
    inspectorId: 'USR-004',
    inspectionType: 'Environment',
    date: '09 Sep 2026',
    time: '09:00 AM',
    status: 'Scheduled',
    priority: 'Urgent',
    purpose: 'Investigate continuous ambient dust exceedance (PM10/PM2.5) and effluent discharge canal.',
    checklistItems: [
      { id: 'chk-1', label: 'Inspect effluent treatment plant (ETP) pH and suspended solids', completed: false },
      { id: 'chk-2', label: 'Verify water sprinkler coverage on main railway siding', completed: false },
      { id: 'chk-3', label: 'Check green belt afforestation boundary survival rate', completed: false },
      { id: 'chk-4', label: 'Audit dust suppression chemical logbooks', completed: false }
    ],
    evidenceFilesCount: 2
  },
  {
    id: 'INS-2399',
    mineId: 'KD-143',
    mineName: 'Korba West Mega Opencast Project',
    inspectorName: 'Anil Kumar',
    inspectorId: 'USR-005',
    inspectionType: 'Full Audit',
    date: '07 Sep 2026',
    time: '02:00 PM',
    status: 'Completed',
    priority: 'Urgent',
    purpose: 'Comprehensive safety, electrical grounding, and HEMM operator license audit.',
    checklistItems: [
      { id: 'chk-1', label: 'Electrical sub-station flame-proof switchgear audit', completed: true, findings: 'Satisfactory grounding recorded.' },
      { id: 'chk-2', label: 'Operator continuous fatigue alert monitoring telemetry', completed: true, findings: '3 cabin cameras disconnected.' },
      { id: 'chk-3', label: 'Blasting storage explosive magazine license verification', completed: true, findings: 'Magazine PESO license verified till Dec 2027.' },
      { id: 'chk-4', label: 'Dump truck proximity detection sensors', completed: true, findings: '2 rear radar units defective.' }
    ],
    observations: 'Issued 2 immediate rectification orders for cabin safety sensors and proximity radar.',
    recommendations: 'Re-inspection required in 14 days after BCCL/SECL submits compliance certificates.',
    evidenceFilesCount: 9
  },
  {
    id: 'INS-2415',
    mineId: 'KD-169',
    mineName: 'Singareni No. 2 Incline & OCP',
    inspectorName: 'Rajesh Sharma, DGMS',
    inspectorId: 'USR-002',
    inspectionType: 'Follow-up',
    date: '14 Sep 2026',
    time: '11:00 AM',
    status: 'Scheduled',
    priority: 'Routine',
    purpose: 'Review leasehold GPS boundary markers and verify rectification of overburden boundary line.',
    checklistItems: [
      { id: 'chk-1', label: 'Verify differential GPS lease boundary pillars', completed: false },
      { id: 'chk-2', label: 'Examine drone photogrammetry verification markers', completed: false }
    ],
    evidenceFilesCount: 1
  }
];

export const INITIAL_VIOLATIONS: Violation[] = [
  {
    id: 'VIO-1024',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    category: 'Safety Compliance',
    severity: 'High',
    description: 'Bench slope steepening observed in Western Sector with crack formation detected along upper berm.',
    issuedDate: '03 Sep 2026',
    deadline: '10 Sep 2026',
    assignedInspector: 'Rajesh Sharma, DGMS',
    status: 'Open',
    correctiveActionText: 'Re-profile the slope angle to 35 degrees, install seismic tiltmeters, and submit slope stability certificate from CIMFR.',
    mineResponse: 'Heavy earth movers deployed to push back top bench. Geo-technical engineer inspecting site.'
  },
  {
    id: 'VIO-1031',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    category: 'Environmental Parameter',
    severity: 'Medium',
    description: 'CAAQMS real-time telemetry detected 24-hour PM10 average at 148 µg/m³ exceeding statutory 100 µg/m³ threshold along Coal Haul Road Corridor 3.',
    issuedDate: '04 Sep 2026',
    deadline: '11 Sep 2026',
    assignedInspector: 'Rajesh Sharma, DGMS',
    status: 'Corrective Action Required',
    correctiveActionText: 'Increase mist cannon water tanker deployment frequency to 30-minute intervals and submit dust suppression telemetry log.',
    mineResponse: 'Two auxiliary 20KL mist sprinkler trucks deployed. Telemetry recalibration report in progress.'
  },
  {
    id: 'VIO-1015',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    category: 'Equipment & Safety',
    severity: 'Medium',
    description: 'Proximity detection radar sensor calibration certificate expired on Dump Truck BCCL-DT-42.',
    issuedDate: '01 Sep 2026',
    deadline: '09 Sep 2026',
    assignedInspector: 'Anil Kumar',
    status: 'Under Review',
    correctiveActionText: 'Recalibrate radar field sensor with OEM technician, conduct blind-spot test, and upload test signoff certificate.',
    mineResponse: 'OEM Bharat Earth Movers Ltd (BEML) completed field sensor recalibration on 03 Sep. Calibration test dossier attached.',
    submittedEvidence: ['BEML_Sensor_Calibration_Certificate.pdf', 'Proximity_Test_Video_Proof.mp4']
  },
  {
    id: 'VIO-1018',
    mineId: 'KD-118',
    mineName: 'Talcher Colliery Complex',
    category: 'Environmental Parameter',
    severity: 'Medium',
    description: 'Effluent discharge from coal washing settling pond exceeded permissible Total Dissolved Solids (TDS) limit.',
    issuedDate: '02 Sep 2026',
    deadline: '12 Sep 2026',
    assignedInspector: 'Sunil Verma',
    status: 'Under Review',
    correctiveActionText: 'Clean settling pit silt accumulation and deploy secondary polymer dosing system.',
    mineResponse: 'Filter press repairs completed on 04 Sep. Water sample test report attached for verification.',
    submittedEvidence: ['ETP_Discharge_Test_Sep2026.pdf', 'Settling_Pond_Photos.jpg']
  },
  {
    id: 'VIO-998',
    mineId: 'KD-143',
    mineName: 'Korba West Mega Opencast Project',
    category: 'Equipment Documentation',
    severity: 'Low',
    description: 'Statutory annual pressure vessel certification expired for compressor bank Unit 4.',
    issuedDate: '01 Sep 2026',
    deadline: '15 Sep 2026',
    assignedInspector: 'Anil Kumar',
    status: 'Evidence Submitted',
    correctiveActionText: 'Perform hydro-testing and submit government authorized competent person certificate.',
    mineResponse: 'Certificate obtained from Bureau Veritas certified inspector on 04 Sep 2026. Document uploaded.',
    submittedEvidence: ['Pressure_Vessel_Cert_BV.pdf']
  },
  {
    id: 'VIO-974',
    mineId: 'KD-202',
    mineName: 'Jharia Block IV Underground Seam',
    category: 'Labour & Welfare',
    severity: 'Medium',
    description: 'Vocational Training Centre (VTC) refresher training records missing for 42 outsourced contractual operators.',
    issuedDate: '26 Aug 2026',
    deadline: '08 Sep 2026',
    assignedInspector: 'Rajesh Sharma, DGMS',
    status: 'Corrective Action Required',
    correctiveActionText: 'Mandatory 3-day refresher batch scheduling and biometric attendance submission.'
  },
  {
    id: 'VIO-950',
    mineId: 'KD-255',
    mineName: 'Belpahar OC Mine',
    category: 'Safety Compliance',
    severity: 'High',
    description: 'Inadequate illumination level in night hauling intersection below statutory 15 Lux requirement.',
    issuedDate: '22 Aug 2026',
    deadline: '05 Sep 2026',
    assignedInspector: 'Sunil Verma',
    status: 'Verified',
    correctiveActionText: 'Install high-mast LED floodlight towers with backup solar battery pack.',
    mineResponse: 'Four 120W mobile LED masts installed. Lux meter survey verified at 24 Lux average.',
    submittedEvidence: ['Lux_Survey_Report.pdf', 'High_Mast_Installation_Photo.jpg']
  }
];

export const INITIAL_CORRECTIVE_ACTIONS: CorrectiveAction[] = [
  {
    id: 'CA-1024',
    violationId: 'VIO-1024',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    title: 'Slope Bench Slope Rectification & Geotechnical Audit',
    instructions: 'Deploy excavator fleet to slice top overhang. Conduct geophysical resistivity profile and upload geotechnical clearance report.',
    severity: 'High',
    dueDate: '10 Sep 2026',
    status: 'Pending Response',
    responseNote: 'Earthwork commenced. Expected completion by 09 Sep.'
  },
  {
    id: 'CA-1031',
    violationId: 'VIO-1031',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    title: 'Coal Haul Corridor 3 Mist Sprinkler & Dust Suppression Protocol',
    instructions: 'Deploy 2 auxiliary mist cannon bowsers and upload 48-hour continuous CAAQMS telemetry export verifying PM10 compliance below statutory limits.',
    severity: 'Medium',
    dueDate: '11 Sep 2026',
    status: 'Pending Response',
    responseNote: 'Bowser fleet deployed. CAAQMS particulate data logging initiated.'
  },
  {
    id: 'CA-1015',
    violationId: 'VIO-1015',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    title: 'Heavy Dumper DT-42 Radar Proximity Sensor Recalibration',
    instructions: 'Perform dynamic obstacle detection test at 10m/20m distance and attach OEM certified test signoff from Bharat Earth Movers Ltd.',
    severity: 'Medium',
    dueDate: '09 Sep 2026',
    status: 'Under Review',
    responseNote: 'BEML engineer completed testing. OEM calibration dossier and test footage submitted.',
    submittedEvidenceFiles: ['BEML_Sensor_Calibration_Certificate.pdf', 'Proximity_Test_Video_Proof.mp4'],
    inspectorRemarks: 'Inspector Anil Kumar reviewing radar calibration test parameters.'
  },
  {
    id: 'CA-1018',
    violationId: 'VIO-1018',
    mineId: 'KD-118',
    mineName: 'Talcher Colliery Complex',
    title: 'Settling Pond De-silting & ETP Rehabilitation',
    instructions: 'Clear secondary filtration pond sludge. Install continuous turbidity probe transmitting to state pollution board.',
    severity: 'Medium',
    dueDate: '12 Sep 2026',
    status: 'Under Review',
    responseNote: 'Sludge extraction completed. Independent water quality laboratory report attached.',
    submittedEvidenceFiles: ['ETP_Discharge_Test_Sep2026.pdf', 'Settling_Pond_Photos.jpg'],
    inspectorRemarks: 'Inspector Sunil Verma verifying telemetry calibration.'
  },
  {
    id: 'CA-998',
    violationId: 'VIO-998',
    mineId: 'KD-143',
    mineName: 'Korba West Mega Opencast Project',
    title: 'Compressor Unit 4 Hydro-test Certification',
    instructions: 'Subject air receivers to hydrostatic test at 1.5x design pressure and submit Form 8 signed by competent engineer.',
    severity: 'Low',
    dueDate: '15 Sep 2026',
    status: 'Evidence Attached',
    responseNote: 'Hydrotest passed with zero pressure drop. Form 8 attached.',
    submittedEvidenceFiles: ['Pressure_Vessel_Cert_BV.pdf']
  }
];

export const INITIAL_DOCUMENTS: MineDocument[] = [
  {
    id: 'DOC-101',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    title: 'MoEFCC Environmental Clearance (EC) - 12.5 MTPA Opencast',
    category: 'Environment',
    fileName: 'MoEFCC_Environmental_Clearance_EC_2026.pdf',
    fileSize: '6.4 MB',
    fileType: 'pdf',
    uploadDate: '15 Jan 2026',
    expiryDate: '31 Dec 2030',
    status: 'Verified'
  },
  {
    id: 'DOC-102',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    title: 'Statutory Quarterly Safety Audit Report Q2-2026',
    category: 'Safety',
    fileName: 'Safety_Audit_Sep2026.pdf',
    fileSize: '4.2 MB',
    fileType: 'pdf',
    uploadDate: '01 Sep 2026',
    expiryDate: '31 Dec 2026',
    status: 'Verified'
  },
  {
    id: 'DOC-103',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    title: 'PESO Heavy Explosive Magazine Storage & Transport License',
    category: 'Compliance',
    fileName: 'PESO_Explosive_Storage_License_2026.pdf',
    fileSize: '3.1 MB',
    fileType: 'pdf',
    uploadDate: '10 Feb 2026',
    expiryDate: '31 Mar 2028',
    status: 'Verified'
  },
  {
    id: 'DOC-104',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    title: 'DGMS Annual Safety & Occupational Health Return (Form III)',
    category: 'Safety',
    fileName: 'DGMS_Annual_Return_Form_III_2026.pdf',
    fileSize: '5.8 MB',
    fileType: 'pdf',
    uploadDate: '20 Jan 2026',
    expiryDate: '31 Jan 2027',
    status: 'Verified'
  },
  {
    id: 'DOC-105',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    title: 'HEMM Heavy Machinery Maintenance & Fitness Dossier',
    category: 'Equipment',
    fileName: 'Equipment_Certificates_BCCL.pdf',
    fileSize: '8.7 MB',
    fileType: 'pdf',
    uploadDate: '28 Aug 2026',
    expiryDate: '30 Jun 2027',
    status: 'Verified'
  },
  {
    id: 'DOC-106',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    title: 'Air & Respirable Dust Concentration Test Results',
    category: 'Environment',
    fileName: 'Dust_Test_Report_Aug2026.pdf',
    fileSize: '2.1 MB',
    fileType: 'pdf',
    uploadDate: '02 Sep 2026',
    status: 'Review'
  },
  {
    id: 'DOC-107',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    title: 'Stage-II Forest Conservation Act (FCA) Diversion Approval',
    category: 'Environment',
    fileName: 'Forest_Clearance_Stage_II_Dhanbad.pdf',
    fileSize: '4.9 MB',
    fileType: 'pdf',
    uploadDate: '05 Mar 2026',
    expiryDate: '15 Mar 2035',
    status: 'Verified'
  },
  {
    id: 'DOC-108',
    mineId: 'KD-104',
    mineName: 'Bharat Coking Coal Mine (Dhanbad)',
    title: 'Blasting Notification & Ground Vibration Velocity Logs',
    category: 'Safety',
    fileName: 'Ground_Vibration_Seismograph.pdf',
    fileSize: '3.6 MB',
    fileType: 'pdf',
    uploadDate: '04 Sep 2026',
    expiryDate: '30 Sep 2026',
    status: 'Verified'
  },
  {
    id: 'DOC-109',
    mineId: 'KD-101',
    mineName: 'Jharia Coking Coal Block',
    title: 'Statutory Mining Lease Deed & DGPS Demarcation Registry',
    category: 'Compliance',
    fileName: 'Mining_Lease_Deed_Jharia_KD101.pdf',
    fileSize: '7.2 MB',
    fileType: 'pdf',
    uploadDate: '12 Jan 2026',
    expiryDate: '31 Dec 2045',
    status: 'Verified'
  },
  {
    id: 'DOC-110',
    mineId: 'KD-101',
    mineName: 'Jharia Coking Coal Block',
    title: 'Consent to Operate (CTO) - State Pollution Control Board',
    category: 'Environment',
    fileName: 'CTO_Air_Water_Jharia_2026.pdf',
    fileSize: '3.4 MB',
    fileType: 'pdf',
    uploadDate: '18 Feb 2026',
    expiryDate: '31 Mar 2027',
    status: 'Verified'
  }
];

export const INITIAL_REPORTS: ReportItem[] = [
  {
    id: 'RPT-2026-091',
    title: 'National Coalfields Compliance & Safety Dossier (August 2026)',
    type: 'Compliance',
    generatedDate: '01 Sep 2026',
    generatedBy: 'System Auto-Engine',
    period: 'August 2026',
    status: 'Available',
    fileFormat: 'PDF'
  },
  {
    id: 'RPT-2026-088',
    title: 'High-Risk Coal Mines Regional Threat Matrix & Action Plan',
    type: 'Risk',
    generatedDate: '28 Aug 2026',
    generatedBy: 'Shri A. K. Sen, IAS',
    period: 'Q2 2026',
    status: 'Available',
    fileFormat: 'PDF'
  },
  {
    id: 'RPT-2026-082',
    title: 'DGMS Comprehensive Field Inspection Performance Review',
    type: 'Inspection',
    generatedDate: '20 Aug 2026',
    generatedBy: 'Rajesh Sharma, DGMS',
    period: 'July-August 2026',
    status: 'Available',
    fileFormat: 'XLSX'
  },
  {
    id: 'RPT-2026-079',
    title: 'Mine Boundary & Drone Volumetric Survey Variance Report',
    type: 'Mine Summary',
    generatedDate: '15 Aug 2026',
    generatedBy: 'CMPDI Technical Cell',
    period: 'H1 2026',
    status: 'Available',
    fileFormat: 'PDF'
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-01',
    title: 'High Priority AI Alert Detected: Boundary Expansion',
    description: 'Mine KD-169 Singareni Colliery flagged for potential perimeter encroachment by AI satellite intelligence.',
    category: 'AI Alerts',
    timestamp: '25 minutes ago',
    read: false,
    roleTarget: 'all',
    linkToModule: 'alerts',
    priority: 'high'
  },
  {
    id: 'NOTIF-02',
    title: 'Statutory Safety Inspection Scheduled for Tomorrow',
    description: 'INS-2408 confirmed for Bharat Coking Coal Mine (Dhanbad) with Inspector Rajesh Sharma.',
    category: 'Inspection Updates',
    timestamp: '2 hours ago',
    read: false,
    roleTarget: 'all',
    linkToModule: 'inspections'
  },
  {
    id: 'NOTIF-03',
    title: 'Urgent Corrective Action Deadline Approaching',
    description: 'VIO-1024 slope stability response is due within 48 hours for Mine KD-104.',
    category: 'Violation Deadlines',
    timestamp: '5 hours ago',
    read: false,
    roleTarget: 'all',
    linkToModule: 'violations',
    priority: 'high'
  },
  {
    id: 'NOTIF-04',
    title: 'Equipment Certificate Verified by Directorate',
    description: 'Hydrotest certificate for Korba West compressor bank verified and approved by Inspector Anil Kumar.',
    category: 'Document Verification',
    timestamp: '1 day ago',
    read: true,
    roleTarget: 'all',
    linkToModule: 'documents'
  },
  {
    id: 'NOTIF-05',
    title: 'Ministry Notification: Enhanced Monsoon Safety Guidelines',
    description: 'All opencast and underground coal authorities must implement standard monsoon sump drainage protocols.',
    category: 'Government Announcements',
    timestamp: '2 days ago',
    read: true,
    roleTarget: 'all',
    linkToModule: 'dashboard'
  }
];
